server.port: 8081

my:
  greeting: Hello World
  list:
       values: one,two,three


db:
  connection: test-connection-string-here
  host: 127.0.0.1
  port: 1800

management.endpoints.web.exposure.include: "*"

app:
  name: My App
  description: Welcome to ${app.name}

 spring.cloud.config.uri: http://localhost:8890

